### ISSUE TITLE
WARNUNG: This OSMedia does not have the latest WSUSXML (Microsoft Updates)

### ISSUE THREAD

**Issue by FLeven** [OSDeploy/OSDBuilder#66] opened 2021-11-10 11:51 UTC
OSDBuilder 21.10.14.1 | OSD 21.11.9.1

Even if I follow:
WARNUNG: Use the following command before running New-OSBuild                                                                                                                                                                                WARNUNG: Update-OSMedia -Name 'Windows Server 2019 Datacenter Desktopdarstellung x64 1809 17763.2300 de-DE' -Download -Execute 

The WARNING will never disappear.

**Comment by GuyEllingham** [comment] 2021-12-15 01:17
+1.
OSDBuilder 21.10.14.1 and OSD 21.11.9.1.
Using Windows 10 x64 21H2 plus November cumulative 5007186 bringing the build to 19044.1348.
I've redownloaded and executed to create updated media but New-OSBuild still produces 'This OSMedia does not have the latest WSUSXML".

**Comment by OSDeploy** [comment] 2021-12-15 15:17
You are going to have to look in the log for the Cumulative Update and see what is preventing the update from applying.  This should be at OSBuilds\<Your OS>\info\logs\*Update-CumulativeOS*.log

**Comment by ps959** [comment] 2022-01-20 18:28
The fix for this for me was to run the commands with Powershell ISE (x64) not the (x86) one. Make sure it's an elevated command prompt. Odd thing is I had to run OSDBUILDER -Update with a non elevated account first.

**Comment by FLeven** [comment] 2022-01-28 10:13
I always run OSDBuider in an Admin-Shell and never use the ISE. The **Warning** still comes up on both 2019 and 2022 Server builds.

**Comment by SilentlyContinue27** [comment] 2022-08-01 17:19
I was experiencing this issue. Updating all modules and restarting VSCode seems to have fixed it for me. I'm not sure if this makes since or not. Maybe my modules were corrupt, and needed to be reinstalled?

OSDBuilder was downloading an older LCU/update list. Confirmed that OSDSUS found the current LCU despite OSDBuilder downloading the old version. I tried Get-DownOSDBuilder, Update-OSMedia, and New-OSBuild with -Download, all referencing the Media name and all download the older LCU. After updating modules, both OSDBuilder and OSDSus get the newest updates.


What I did to fix it:
        #Update:
        Get-OSDBuilder -SetPath  $OSDBuilderPath -UpdateModule
        Import-Module OSDBuilder
        Import-Module OSD
        Update-OSDSus
        Import-Module OSDSus
        Write-Host "Now close and re-run Powershell/VSCode as admin/elevated." -foregroundcolor yellow

get-module osd* | select Name, Version | fl
Name    : OSD
Version : 22.7.12.1 ( previously 22.7.11.1 before update fixed the process )
Name    : OSDBuilder
Version : 22.4.20.1 ( Same )
Name    : osdsus
Version : 22.7.12.1 ( Same )



VSCode info:
Version: 1.69.2 (system setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044
Powershell Module v2022.7.2
Run as Elevated Admin


Media: 
MediaType        : OSMedia
ModifiedTime     : 7/27/2022 4:34:12 PM
Superseded       : False
NeedsUpdate      : True
Revision         : OK
Updates          : Update
Name             : Windows 10 Enterprise x64 21H2 19044.1766 ( OSDBuilder could not update beyond this until I updated modules and restarted VSCode )
OperatingSystem  : Windows 10
Arch             : x64
ReleaseId        : 21H2
RegBuild         : 19044
UBR              : 19044.1766
Version          : 10.0.19044.1766
MajorVersion     : 10
MinorVersion     : 0
Build            : 19044
Languages        : {en-US}
EditionId        : Enterprise
InstallationType : Client
ImageName        : Windows 10 Enterprise
OSMFamily        : Client Enterprise x64 19044 en-US
FullName         : C:\Power\OSDBuilder\OSMedia\Windows 10 Enterprise x64 21H2 19044.1766
CreatedTime      : 3/3/2022 2:17:59 AM
OSMGuid          : aaf88d50-c7d7-4eaf-b167-71b2ca1453da
OSMFamilyV1      : 20220303021759Enterprise

Old Updates downloaded by OSDBuilder ( Before updating the module, it is now getting newest ):
ssu-19041.1704-x64_c01ad66716dc695d7aa1afab622e2d8be0eb2d65.cab
windows10.0-kb5007401-x64_f1bf61d834bb8d9951c7efa23454643daae195b0.cab
windows10.0-kb5010524-x64_39a338080df5a19e491a1f19ac57117cb8944cba.cab
windows10.0-kb5011577-x64_f6239f5a4459e95dbd3346f178e2836a19f42586.cab
windows10.0-kb5013624-x64-ndp48_6f79154c6a693ba11ccaf009e3f65c70ccbda282.cab
windows10.0-kb5013887-x64-ndp48_aa0da938276607c9736d87066ade1776dafd7aa5.cab
windows10.0-kb5014699-x64_202eb4370b02f689b4904b69f13076b66ce5e1f1.cab


Correct/Newest Updates found by OSDSus: 
get-osdsus -updatearch x64 -updatebuild 21h2 -updateos "Windows 10"  | where { $PSITEM.updategroup -notlike $Null}  | select kbnumber, updategroup, filename
KBNumber UpdateGroup             FileName
-------- -----------                          --------
5015807  LCU                                Windows10.0-KB5015807-x64.cab
5013887  DotNetCU                      Windows10.0-KB5013887-x64-NDP48.cab
5014032  SSU                                 SSU-19041.1704-x64.cab
5013624  DotNetCU                       Windows10.0-KB5013624-x64-NDP48.cab
5011577  ComponentDU SafeOS   Windows10.0-KB5011577-x64.cab
5010524  SetupDU                          Windows10.0-KB5010524-x64.cab
5007401  ComponentDU                Critical Windows10.0-KB5007401-x64.cab

**Closed** 2023-01-22 20:37 UTC
